name: GAB2021 Build

on:
  push:
    paths:
    - 'SampleWeb/**'
    branches: [ master ]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Get code from the repository
      uses: actions/checkout@v1
      with:
        ref: master

    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}  
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        path: './SampleWeb'
        dockerfile: './SampleWeb/Dockerfile'
        repository: 'sampleweb'
        tags: 'latest'
        push: true
    # Deploy to AKS
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: wgaks2
        resource-group: rg-ga2021
        
    - uses: Azure/k8s-create-secret@v1
      with:
        container-registry-url: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: demo-k8s-secret

    - uses: Azure/k8s-deploy@v1.4
      with:
        manifests: |
          ./yaml/deployment.yaml
        images: |
          ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleweb:latest
        imagepullsecrets: |
          demo-k8s-secret
